name: Bug Report
description: Report a bug in Watch My SaaS
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Send a webhook with...
        2. Check the dashboard...
        3. See error...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Deployment method, version, etc.
      placeholder: |
        - Watch My SaaS version: 0.1.0
        - Deployment: Docker Compose / Render
        - Node.js version: 20.x

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error messages or logs
      render: shell
