name: Copilot Task
description: Well-scoped task for Copilot Coding Agent
labels: ["copilot-task"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: What needs to be done? Be specific.
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Files to Touch
      description: List every file this task should modify or create.
      placeholder: |
        - src/services/classification.ts (modify)
        - src/__tests__/services/classification.test.ts (modify)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done? Must be testable by CI.
      placeholder: |
        - [ ] All tests pass
        - [ ] tsc --noEmit succeeds
        - [ ] Coverage >= 80%
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context the agent needs. Include relevant code patterns or references.
